class Board < ActiveRecord::Base
	has_many :teams
	has_many :players
	has_many :picks

	accepts_nested_attributes_for :picks, :players, :teams

	attr_accessor :make_pick
	attr_accessor :update_current_pick

	def make_pick

	end

	def set_up_board
		Team.create(city: "Atlanta", nickname: "Hawks", logo: "hawks.png", board_id: self.id)
		Team.create(city: "Boston", nickname: "Celtics", logo: "celtics.png", board_id: self.id)
		Team.create(city: "Brooklyn", nickname: "Nets", logo: "nets.png", board_id: self.id)
		Team.create(city: "Charlotte", nickname: "Hornets", logo: "hornets.png", board_id: self.id)
		Team.create(city: "Chicago", nickname: "Bulls", logo: "bulls.png", board_id: self.id)
		Team.create(city: "Cleveland", nickname: "Cavaliers", logo: "cavaliers.png", board_id: self.id)
		Team.create(city: "Dallas", nickname: "Mavericks", logo: "mavericks.png", board_id: self.id)
		Team.create(city: "Denver", nickname: "Nuggets", logo: "nuggets.png", board_id: self.id)
		Team.create(city: "Detroit", nickname: "Pistons", logo: "pistons.png", board_id: self.id)
		Team.create(city: "Golden State", nickname: "Warriors", logo: "warriors.png", board_id: self.id)
		Team.create(city: "Houston", nickname: "Rockets", logo: "rockets.png", board_id: self.id)
		Team.create(city: "Indiana", nickname: "Pacers", logo: "pacers.png", board_id: self.id)
		Team.create(city: "Los Angeles", nickname: "Clippers", logo: "clippers.png", board_id: self.id)
		Team.create(city: "Los Angeles", nickname: "Lakers", logo: "lakers.png", board_id: self.id)
		Team.create(city: "Memphis", nickname: "Grizzlies", logo: "grizzlies.png", board_id: self.id)
		Team.create(city: "Miami", nickname: "Heat", logo: "heat.png", board_id: self.id)
		Team.create(city: "Milwaukee", nickname: "Bucks", logo: "bucks.png", board_id: self.id)
		Team.create(city: "Minnesota", nickname: "Timberwolves", logo: "timberwolves.png", board_id: self.id)
		Team.create(city: "New Orleans", nickname: "Pelicans", logo: "pelicans.png", board_id: self.id)
		Team.create(city: "New York", nickname: "Knicks", logo: "knicks.png", board_id: self.id)
		Team.create(city: "Oklahoma City", nickname: "Thunder", logo: "thunder.png", board_id: self.id)
		Team.create(city: "Orlando", nickname: "Magic", logo: "magic.png", board_id: self.id)
		Team.create(city: "Philadelphia", nickname: "76ers", logo: "76ers.png", board_id: self.id)
		Team.create(city: "Phoenix", nickname: "Suns", logo: "suns.png", board_id: self.id)
		Team.create(city: "Portland", nickname: "Trail Blazers", logo: "trailblazers.png", board_id: self.id)
		Team.create(city: "Sacramento", nickname: "Kings", logo: "kings.png", board_id: self.id)
		Team.create(city: "San Antonio", nickname: "Spurs", logo: "spurs.png", board_id: self.id)
		Team.create(city: "Toronto", nickname: "Raptors", logo: "raptors.png", board_id: self.id)
		Team.create(city: "Utah", nickname: "Jazz", logo: "jazz.png", board_id: self.id)
		Team.create(city: "Washington", nickname: "Wizards", logo: "wizards.png", board_id: self.id)
		Pick.create(draft_pick: 1, round: 1, value: 100, board_id: self.id, current_pick: true)
		Pick.create(draft_pick: 2, round: 1, value: 95, board_id: self.id)
		Pick.create(draft_pick: 3, round: 1, value: 77, board_id: self.id)
		Pick.create(draft_pick: 4, round: 1, value: 70, board_id: self.id)
		Pick.create(draft_pick: 5, round: 1, value: 65, board_id: self.id)
		Pick.create(draft_pick: 6, round: 1, value: 60, board_id: self.id)
		Pick.create(draft_pick: 7, round: 1, value: 56, board_id: self.id)
		Pick.create(draft_pick: 8, round: 1, value: 53, board_id: self.id)
		Pick.create(draft_pick: 9, round: 1, value: 50, board_id: self.id)
		Pick.create(draft_pick: 10, round: 1, value: 47, board_id: self.id)
		Pick.create(draft_pick: 11, round: 1, value: 45, board_id: self.id)
		Pick.create(draft_pick: 12, round: 1, value: 43, board_id: self.id)
		Pick.create(draft_pick: 13, round: 1, value: 41, board_id: self.id)
		Pick.create(draft_pick: 14, round: 1, value: 39, board_id: self.id)
		Pick.create(draft_pick: 15, round: 1, value: 37, board_id: self.id)
		Pick.create(draft_pick: 16, round: 1, value: 35, board_id: self.id)
		Pick.create(draft_pick: 17, round: 1, value: 34, board_id: self.id)
		Pick.create(draft_pick: 18, round: 1, value: 33, board_id: self.id)
		Pick.create(draft_pick: 19, round: 1, value: 31, board_id: self.id)
		Pick.create(draft_pick: 20, round: 1, value: 30, board_id: self.id)
		Pick.create(draft_pick: 21, round: 1, value: 29, board_id: self.id)
		Pick.create(draft_pick: 22, round: 1, value: 27, board_id: self.id)
		Pick.create(draft_pick: 23, round: 1, value: 26, board_id: self.id)
		Pick.create(draft_pick: 24, round: 1, value: 25, board_id: self.id)
		Pick.create(draft_pick: 25, round: 1, value: 24, board_id: self.id)
		Pick.create(draft_pick: 26, round: 1, value: 23, board_id: self.id)
		Pick.create(draft_pick: 27, round: 1, value: 22, board_id: self.id)
		Pick.create(draft_pick: 28, round: 1, value: 21, board_id: self.id)
		Pick.create(draft_pick: 29, round: 1, value: 21, board_id: self.id)
		Pick.create(draft_pick: 30, round: 1, value: 20, board_id: self.id)
		Pick.create(draft_pick: 31, round: 2, value: 19, board_id: self.id)
		Pick.create(draft_pick: 32, round: 2, value: 18, board_id: self.id)
		Pick.create(draft_pick: 33, round: 2, value: 17, board_id: self.id)
		Pick.create(draft_pick: 34, round: 2, value: 16, board_id: self.id)
		Pick.create(draft_pick: 35, round: 2, value: 15, board_id: self.id)
		Pick.create(draft_pick: 36, round: 2, value: 14, board_id: self.id)
		Pick.create(draft_pick: 37, round: 2, value: 13, board_id: self.id)
		Pick.create(draft_pick: 38, round: 2, value: 12, board_id: self.id)
		Pick.create(draft_pick: 39, round: 2, value: 11, board_id: self.id)
		Pick.create(draft_pick: 40, round: 2, value: 10, board_id: self.id)
		Pick.create(draft_pick: 41, round: 2, value: 9, board_id: self.id)
		Pick.create(draft_pick: 42, round: 2, value: 8, board_id: self.id)
		Pick.create(draft_pick: 43, round: 2, value: 7, board_id: self.id)
		Pick.create(draft_pick: 44, round: 2, value: 6, board_id: self.id)
		Pick.create(draft_pick: 45, round: 2, value: 5, board_id: self.id)
		Pick.create(draft_pick: 46, round: 2, value: 5, board_id: self.id)
		Pick.create(draft_pick: 47, round: 2, value: 4, board_id: self.id)
		Pick.create(draft_pick: 48, round: 2, value: 4, board_id: self.id)
		Pick.create(draft_pick: 49, round: 2, value: 4, board_id: self.id)
		Pick.create(draft_pick: 50, round: 2, value: 3, board_id: self.id)
		Pick.create(draft_pick: 51, round: 2, value: 3, board_id: self.id)
		Pick.create(draft_pick: 52, round: 2, value: 3, board_id: self.id)
		Pick.create(draft_pick: 53, round: 2, value: 2, board_id: self.id)
		Pick.create(draft_pick: 54, round: 2, value: 2, board_id: self.id)
		Pick.create(draft_pick: 55, round: 2, value: 2, board_id: self.id)
		Pick.create(draft_pick: 56, round: 2, value: 2, board_id: self.id)
		Pick.create(draft_pick: 57, round: 2, value: 1, board_id: self.id)
		Pick.create(draft_pick: 58, round: 2, value: 1, board_id: self.id)
		Pick.create(draft_pick: 59, round: 2, value: 1, board_id: self.id)
		Pick.create(draft_pick: 60, round: 2, value: 1, board_id: self.id)
		Player.create(first_name:  "Ben" , last_name:  "Simmons" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  1, value:  93, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Brandon" , last_name:  "Ingram" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  2, value:  87, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Dragan" , last_name:  "Bender" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  3, value:  73, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Kris" , last_name:  "Dunn" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  4, value:  70, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jaylen" , last_name:  "Brown" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  5, value:  65, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jamal" , last_name:  "Murray" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  6, value:  60, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jakob" , last_name:  "Poeltl" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  7, value:  56, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Buddy" , last_name:  "Hield" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  8, value:  53, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Henry" , last_name:  "Ellenson" , position:  "PF-C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  9, value:  50, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Denzel" , last_name:  "Valentine" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  10, value:  47, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Domantas" , last_name:  "Sabonis" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  11, value:  45, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Timothe" , last_name:  "Luwawu" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  12, value:  43, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Deyonta" , last_name:  "Davis" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  13, value:  41, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Skal" , last_name:  "Labissiere" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  14, value:  39, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Tyler" , last_name:  "Ulis" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  15, value:  37, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Furkan" , last_name:  "Korkmaz" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  16, value:  35, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Marquese" , last_name:  "Chriss" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  17, value:  34, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Demetrius" , last_name:  "Jackson" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  18, value:  33, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Wade" , last_name:  "Baldwin IV" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  19, value:  31, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Malik" , last_name:  "Beasley" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  20, value:  30, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Taurean" , last_name:  "Prince" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  21, value:  29, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Ante" , last_name:  "Zizic" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  22, value:  27, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Brice" , last_name:  "Johnson" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  23, value:  26, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Juan" , last_name:  "Hernangomez" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  24, value:  25, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "DeAndre'" , last_name:  "Bembry" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  25, value:  24, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Thon" , last_name:  "Maker" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  26, value:  23, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Ivica" , last_name:  "Zubac" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  27, value:  22, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Stephen" , last_name:  "Zimmerman Jr." , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  28, value:  21, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Diamond" , last_name:  "Stone" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  29, value:  21, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Malcolm" , last_name:  "Brogdon" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  30, value:  20, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "A.J." , last_name:  "Hammons" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  31, value:  19, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Damian" , last_name:  "Jones" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  32, value:  18, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Dejounte" , last_name:  "Murray" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  33, value:  17, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Isaia" , last_name:  "Cordinier" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  34, value:  17, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Petr" , last_name:  "Cornelie" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  35, value:  16, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Paul" , last_name:  "Zipser" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  36, value:  15, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Zhou" , last_name:  "Qi" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  37, value:  14, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Ben" , last_name:  "Bentil" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  38, value:  14, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Patrick" , last_name:  "McCaw" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  39, value:  13, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Chinanu" , last_name:  "Onuaku" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  40, value:  12, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Melo" , last_name:  "Trimble" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  41, value:  12, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Sheldon" , last_name:  "McClellan" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  42, value:  11, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Isaiah" , last_name:  "Whitehead" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  43, value:  11, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Cheick" , last_name:  "Diallo" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  44, value:  10, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Caris" , last_name:  "LeVert" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  45, value:  9, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Gary" , last_name:  "Payton II" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  46, value:  9, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Dedric" , last_name:  "Lawson" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  47, value:  8, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Nigel" , last_name:  "Hayes" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  48, value:  8, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Kahlil" , last_name:  "Felder" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  49, value:  7, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Malik" , last_name:  "Newman" , position:  "G" , height:  "6-8" , old_team:  "LSU" , mock_rank:  50, value:  7, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Wayne" , last_name:  "Selden Jr." , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  51, value:  6, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Perry" , last_name:  "Ellis" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  52, value:  6, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jake" , last_name:  "Layman" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  53, value:  6, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jarrod" , last_name:  "Uthoff" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  54, value:  6, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Georgios" , last_name:  "Papagiannis" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  55, value:  6, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Pascal" , last_name:  "Siakam" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  56, value:  5, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Yogi" , last_name:  "Ferrell" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  57, value:  5, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jaron" , last_name:  "Blossomgame" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  58, value:  5, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Josh" , last_name:  "Hart" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  59, value:  5, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Damion" , last_name:  "Lee" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  60, value:  5, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Rade" , last_name:  "Zagorac" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  61, value:  4, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Michael" , last_name:  "Gbinije" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  62, value:  4, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Sasha" , last_name:  "Vezenkov" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  63, value:  4, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Guerschon" , last_name:  "Yabusele" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  64, value:  4, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Malachi" , last_name:  "Richardson" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  65, value:  4, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Daniel" , last_name:  "Hamilton" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  66, value:  3, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Troy" , last_name:  "Williams" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  67, value:  3, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Dorian" , last_name:  "Finney-Smith" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  68, value:  3, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Shawn" , last_name:  "Long" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  69, value:  3, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Fred" , last_name:  "VanVleet" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  70, value:  3, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Anthony" , last_name:  "Barber" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  71, value:  2, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Dillon" , last_name:  "Brooks" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  72, value:  2, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Kyle" , last_name:  "Wiltjer" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  73, value:  2, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Joel" , last_name:  "Bolomboy" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  74, value:  2, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jameel" , last_name:  "Warney" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  75, value:  2, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Malik" , last_name:  "Pope" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  76, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Justin" , last_name:  "Jackson" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  77, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Prince" , last_name:  "Ibeh" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  78, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Alpha" , last_name:  "Kaba" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  79, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Josh" , last_name:  "Adams" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  80, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Isaiah" , last_name:  "Taylor" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  81, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "James" , last_name:  "Webb III" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  82, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Marko" , last_name:  "Arapovic" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  83, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Marcus" , last_name:  "Paige" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  84, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Charles" , last_name:  "Cooke" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  85, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Danuel" , last_name:  "House" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  86, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Robert" , last_name:  "Carter" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  87, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Georges" , last_name:  "Niang" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  88, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Tyler" , last_name:  "Dorsey" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  89, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Caleb" , last_name:  "Swanigan" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  90, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Ron" , last_name:  "Baker" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  91, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Vince" , last_name:  "Edwards" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  92, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Julian" , last_name:  "Jacobs" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  93, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Andrey" , last_name:  "Desyatnikov" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  94, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Isaiah" , last_name:  "Briscoe" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  95, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Zach" , last_name:  "Auguste" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  96, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Egemen" , last_name:  "Guven" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  97, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Alex" , last_name:  "Caruso" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  98, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Wes" , last_name:  "Washpun" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  99, value:  1, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Elgin" , last_name:  "Cook" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  100, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Blaz" , last_name:  "Mesicek" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  101, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Moses" , last_name:  "Kingsley" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  102, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "James" , last_name:  "Blackmon Jr." , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  103, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Derrick" , last_name:  "Jones Jr." , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  104, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Tonye" , last_name:  "Jekiri" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  105, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "A.J." , last_name:  "English" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  106, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Diego" , last_name:  "Flaccadori" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  107, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Alex" , last_name:  "Poythress" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  108, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Axel" , last_name:  "Bouteille" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  109, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Tyrone" , last_name:  "Wallace" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  110, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Marcus" , last_name:  "Lee" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  111, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Trevon" , last_name:  "Bluiett" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  112, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Nik" , last_name:  "Slavica" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  113, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Alec" , last_name:  "Peters" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  114, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Marius" , last_name:  "Grigonis" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  115, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Tim" , last_name:  "Quarterman" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  116, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Zeek" , last_name:  "Woodley" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  117, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Josh" , last_name:  "Scott" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  118, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Amida" , last_name:  "Brimah" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  119, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Bryn" , last_name:  "Forbes" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  120, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Isaiah" , last_name:  "Miles" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  121, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Egidijus" , last_name:  "Mockevicius" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  122, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Moussa" , last_name:  "Diagne" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  123, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Kaleb" , last_name:  "Tarczewski" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  124, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Nathan" , last_name:  "Boothe" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  125, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Daniel" , last_name:  "Ochefu" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  126, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "David" , last_name:  "Walker" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  127, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Brannen" , last_name:  "Greene" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  128, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Kyle" , last_name:  "Collinsworth" , position:  "G" , height:  "6-8" , old_team:  "LSU" , mock_rank:  129, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Thomas" , last_name:  "Walkup" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  130, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Cameron" , last_name:  "Oliver" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  131, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Emircan" , last_name:  "Kosut" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  132, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Edin" , last_name:  "Atic" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  133, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Peter" , last_name:  "Jok" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  134, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Wang" , last_name:  "Zhelin" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  135, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Ryan" , last_name:  "Anderson" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  136, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Kenan" , last_name:  "Sipahi" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  137, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Shevon" , last_name:  "Thompson" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  138, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Mamadou" , last_name:  "Ndiaye" , position:  "C" , height:  "6-8" , old_team:  "LSU" , mock_rank:  139, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Stefan" , last_name:  "Jankovic" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  140, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Jalen" , last_name:  "Moore" , position:  "SF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  141, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Shavon" , last_name:  "Shields" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  142, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Devin" , last_name:  "Williams" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  143, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Andrew" , last_name:  "Andrews" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  144, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Maurice" , last_name:  "Watson Jr." , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  145, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Kevin" , last_name:  "Punter Jr." , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  146, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Retin" , last_name:  "Obasohan" , position:  "PG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  147, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Abdul-Malik" , last_name:  "Abu" , position:  "PF" , height:  "6-8" , old_team:  "LSU" , mock_rank:  148, value:  0, board_id: self.id, is_selected?: false)
		Player.create(first_name:  "Marvelle" , last_name:  "Harris" , position:  "SG" , height:  "6-8" , old_team:  "LSU" , mock_rank:  149, value:  0, board_id: self.id, is_selected?: false)
	end


end
